---
- name: Create a local user account
  hosts: 10.10.1.56
  become: yes
  vars:
          - ansible_sudo_pass: P@ssw0rd
            gather_facts: true

  tasks:
    - name: create a user
      user:
        name: TestUser1
        password: "{{ 'WGU123' | password_hash('sha512') }}"
        state: present
        shell: /bin/bash
        home: /home/TestUser1
        create_home: yes

- name: Create a local user account
  hosts: 10.10.1.57
  become: yes
  vars:
          - ansible_sudo_pass: P@ssw0rd
            gather_facts: true

  tasks:
    - name: create a user
      user:
        name: TestUser2
        password: "{{ 'WGU123' | password_hash('sha512') }}"
        state: present
        shell: /bin/bash
        home: /home/TestUser2
        create_home: yes


